### ISSUE TITLE
Missing template in the example

### ISSUE THREAD

**Issue by thibaudcolas** [bashu/wagtail-metadata-mixin#1]
In its [`page.html`](https://github.com/bashu/wagtail-metadata-mixin/blob/develop/example/demoapp/templates/demoapp/page.html) template, the example has an include to a `meta/meta.html` which doesn't exist in the repository.

**Comment by bashu** [comment]
Hey @thibaudcolas 

`meta/meta.html` is a part of https://github.com/nephila/django-meta package which itself a mandatory requirements of this app
