### ISSUE TITLE
Wagtail 2.9 / Django 3.0

### ISSUE THREAD

**Issue by sekanitembo** [bashu/wagtail-metadata-mixin#10]
I created a PR (#9)  to support Wagtail 2.9 / Django 3.0. Let me know what you think/if it needs changes. Thanks.

**Comment by sekanitembo** [comment]
I created a new PR (#11) to fix a bug in previous PR and test across supported environments with tox.

**Comment by bashu** [comment]
fixed in https://github.com/bashu/wagtail-metadata-mixin/releases/tag/0.0.8
