### ISSUE TITLE
incompatible with django-meta 2.0.0

### ISSUE THREAD

**Issue by killarny** [bashu/wagtail-metadata-mixin#12]
As of Nov 14th, django-meta has been updated with backwards incompatible changes, and produces errors when installed according to the `install_requires` keyword value provided by the setup.py in wagtail-metadata-mixin (it specifies `"django-meta>1.5"`.)

Attempting to run a wagtail project with wagtail-metadata-mixin now produces this exception:
```
  File "/usr/local/lib/python3.7/site-packages/wagtailmetadata/models.py", line 9, in <module>
    from meta_mixin.models import ModelMeta
ModuleNotFoundError: No module named 'meta_mixin'
```
Pinning the version of django-meta in my wagtail project requirements as `"django-meta>1.5,<2"` instead appears to resolve the problem for now.

**Comment by YasielCabrera** [comment]
Same here! Also fixed the issue pinning the `django-meta` version

**Comment by bashu** [comment]
as temporary solution use version 0.0.9

**Comment by bashu** [comment]
to @killarny and @YasielCabrera try:
```sh
pip install -U wagtail-metadata-mixin
```
